### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by hulucc** [net-reflow/reflow#11]
win10 64bit 1803

![image](https://user-images.githubusercontent.com/4343900/52562107-5627b580-2e38-11e9-8b99-310d11311978.png)

![image](https://user-images.githubusercontent.com/4343900/52562069-40b28b80-2e38-11e9-8c7a-d0ea81a74425.png)

**Comment by bitsmut** [comment]
@hulucc the domains all seem to be truncated, ending with `.c` instead of `.com`. please elaborate on the application being used. could you check whether it's making requests with correct headers? a packet capture with wireshark would be very helpful

**Comment by prooxidant** [comment]
@hulucc fixed in latest revision
